### ISSUE TITLE
extractorRunner hanging problem

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#273]
I am using develop branch:

```
15:43:10 [DataLoader(akka://deepdive)] INFO  gpload -f /tmp/gpload9045506308201380182.yml
15:43:10 [Helpers$(akka://deepdive)] INFO  Executing command: "/tmp/gpload5879879319714338796.sh"
15:43:10 [Helpers$(akka://deepdive)] INFO  /tmp/gpload5879879319714338796.sh: line 1: gpload: command not f
ound
15:43:10 [extractorRunner-ext_mention] ERROR Failure when executing script: /tmp/gpload58798793197[48/1392]
sh
java.lang.RuntimeException: Failure when executing script: /tmp/gpload5879879319714338796.sh
        at org.deepdive.helpers.Helpers$.executeCmd(Helpers.scala:102) ~[deepdive_2.10-0.0.3.jar:0.0.3]
        at org.deepdive.datastore.DataLoader.load(Dataloader.scala:141) ~[deepdive_2.10-0.0.3.jar:0.0.3]
        at org.deepdive.extraction.ExtractorRunner.org$deepdive$extraction$ExtractorRunner$$runTsvExtractor
(ExtractorRunner.scala:492) ~[deepdive_2.10-0.0.3.jar:0.0.3]
        at org.deepdive.extraction.ExtractorRunner$$anonfun$2.applyOrElse(ExtractorRunner.scala:131) ~[deep
dive_2.10-0.0.3.jar:0.0.3]
        at org.deepdive.extraction.ExtractorRunner$$anonfun$2.applyOrElse(ExtractorRunner.scala:100) ~[deep
dive_2.10-0.0.3.jar:0.0.3]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.
10.5.jar:na]
        at akka.actor.FSM$class.processEvent(FSM.scala:587) ~[akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at org.deepdive.extraction.ExtractorRunner.processEvent(ExtractorRunner.scala:59) ~[deepdive_2.10-0
.0.3.jar:0.0.3]
        at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:581) ~[akka-actor_2.10-2.3-M2.jar:2.3-
M2]
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:575) ~[akka-actor_2.10-2.3-M2.jar:2.3-M2
]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at org.deepdive.extraction.ExtractorRunner.aroundReceive(ExtractorRunner.scala:59) ~[deepdive_2.10-
0.0.3.jar:0.0.3]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:491) [akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:462) [akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237) [akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at akka.dispatch.Mailbox.run(Mailbox.scala:219) [akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) [
akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.5.jar:n
a]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-
2.10.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.5.j
ar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library
-2.10.5.jar:na]
15:43:10 [extractorRunner-ext_mention] INFO  waiting for tasks
15:43:10 [extractorRunner-ext_mention] WARN  unhandled event PrintStatus in state Idle
15:43:40 [extractorRunner-ext_mention] WARN  unhandled event PrintStatus in state Idle
```

Then it hangs there. I should have fixed it before... need to check.

**Comment by netj** [comment]
Greenplum (`gpload`) seems to be not on PATH.  As there are so many environment variables that can go wrong, it may be a good idea to perform some form of runtime dependency check from Main.  A very limited check is done at build/install time by #266, but we'll need different checks based on what database is used.  These could be added as basic sanity checks for application.conf, e.g., checking the udf codes, database connections, etc.
