### ISSUE TITLE
Failure in format_converter – system idle

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#381]
See log below. There are two issues here:

1.  I am getting a java.lang.NoClassDefFoundError when running format_converter.
2.  The error is only reported on the console, but not in the error log file. After that, the system goes into an idle state, where to_binary.py is no longer running; however the DD process is, and there seems to be no activity. Unfortunately, the relevant files eg. dd_variables_rates are deleted when this error occurs making it time-consuming to re-run.

I've reproduced this error twice.

```
17:30:11 [PostgresInferenceRunnerComponent$PostgresInferenceRunner(akka://deepdive)] INFO  Converting grounding file format...
17:30:11 [PostgresInferenceRunnerComponent$PostgresInferenceRunner(akka://deepdive)] DEBUG Executing: python /lfs/raiders4/1/raphaelh/dd/new/deepdive/util/tobinary.py /lfs/raide
rs4/1/raphaelh/dd/new/deepdive/out /lfs/raiders4/1/raphaelh/dd/new/deepdive/util/format_converter /lfs/raiders4/1/raphaelh/dd/new/deepdive/out
17:30:53 [taskManager] INFO  Memory usage: 721/2082MB (max: 27305MB)
17:31:53 [taskManager] INFO  Memory usage: 721/2082MB (max: 27305MB)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Thread-15"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Thread-14"
17:32:53 [taskManager] INFO  Memory usage: 721/2082MB (max: 27305MB)
17:33:53 [taskManager] INFO  Memory usage: 721/2082MB (max: 27305MB)
17:34:53 [taskManager] INFO  Memory usage: 722/2082MB (max: 27305MB)
17:35:53 [taskManager] INFO  Memory usage: 722/2082MB (max: 27305MB)
...
```

**Comment by alldefector** [comment]
Based on my experience with Java, NoClassDefFoundError might occur when a
thread is cleaned up (some sort of race condition between the user code and
JVM's thread manager I think). The DD log file is still printing every
minute:

21:05:53.772 [default-dispatcher-3][taskManager][TaskManager] INFO  Memory
usage: 107/2101MB (max: 27305MB)
21:06:53.772 [default-dispatcher-3][taskManager][TaskManager] INFO  Memory
usage: 107/2101MB (max: 27305MB)
21:07:53.772 [default-dispatcher-3][taskManager][TaskManager] INFO  Memory
usage: 107/2101MB (max: 27305MB)
21:08:53.772 [default-dispatcher-3][taskManager][TaskManager] INFO  Memory
usage: 108/2101MB (max: 27305MB)
...

But looks like it's just akka puking -- I don't see tobinary.py or
format_converter running.

Does the converter or the python script print out logs that are not
redirected by Java? Those logs would be useful. Maybe generate the input
file and halt DD and then run the converter manually so we can see the logs.

**Comment by raphaelhoffmann** [comment]
>
> Does the converter or the python script print out logs that are not
> redirected by Java? Those logs would be useful. Maybe generate the input
> file and halt DD and then run the converter manually so we can see the
> logs.
>

That sounds good – I'll run this overnight.

**Comment by raphaelhoffmann** [comment]
OK. It's restarted. In both cases when I got this error, I also had to later start a new shell, since simply re-running DD threw the following error:

```
./run.sh
java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at xsbt.boot.Locks$.apply0(Locks.scala:35)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at xsbt.boot.Launch.locked(Launch.scala:178)
        at xsbt.boot.Launch.app(Launch.scala:93)
        at xsbt.boot.Launch.app(Launch.scala:91)
        at xsbt.boot.Launch$.run(Launch.scala:51)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.IOException: Permission denied
```

**Comment by SenWu** [comment]
@raphaelhoffmann You lost permission when you re-run DD. You can either re-login or use reauth command to get authenticated access.

**Comment by raphaelhoffmann** [comment]
@SenWu I see – but I don't understand why this is happening. What is
causing this?

**Comment by SenWu** [comment]
@raphaelhoffmann It might be your DD installation. Did you install your DD/sbt in afs? If all your installations (sbt, DD) are in lfs, then everything will be fine.

**Comment by raphaelhoffmann** [comment]
Not sure what it's trying to create in /afs, but you're right: It appears
to be some Stanford security policy. Thanks.

**Comment by alldefector** [comment]
@zhangce is working on the next-gen petabyte-scale sampler that will do without the object boxing and converter!

**Comment by raphaelhoffmann** [comment]
This issue is resolved. Thanks for the helpful tip, @SenWu !

Although I didn't have ```sbt``` installed locally, I was using the sbt launcher in the DeepDive directory ```sbt/sbt "run ..."```.  Without further arguments, it puts ivy packages and lock files into the user's home directory. The errors went away, when explicitly instructing sbt to use different paths:

``` 
java -Dsbt.global.base=/lfs/local/1/raphaelh/.sbt -Dsbt.ivy.home=/lfs/local/1/raphaelh/.ivy2 -Divy.home=/lfs/local/1/raphaelh/.ivy2 -jar sbt/sbt-launch.jar "run -c $DIRNAME/deepdive.conf -o $TMP_DIR"
```

I think it would make sense to set these paths automatically in the DeepDive launch script, or perhaps at least warn/document somewhere, since many of us are running DeepDive on Stanford machines and will inevitably run into this problem when running larger datasets.
