### ISSUE TITLE
Failed installation for run_deepdive_tests

### ISSUE THREAD

**Issue by ukliu** [HazyResearch/deepdive#400]
Hi there. I am a newbie trying to install deepdive together with PostgreSQL. I followed the installation guild on http://deepdive.stanford.edu/doc/basics/installation.html. All seem working but when I ran run_deepdive_tests, it says this,

```
.........(abbreviated)
x deepdive-0.7.0/test/postgresql/should-work.sh
x deepdive-0.7.0/test/postgresql/spouse_example
x deepdive-0.7.0/test/postgresql/spouse_example.bats
x deepdive-0.7.0/test/postgresql/spouse_example.helpers.sh
x deepdive-0.7.0/test/postgresql/spouse_example_incremental.bats
x deepdive-0.7.0/test/postgresql/update-scalatests.bats.sh
x deepdive-0.7.0/test/test_plpy.bats
x deepdive-0.7.0/util/test/
x deepdive-0.7.0/util/test/cosine_similarity_of
x deepdive-0.7.0/util/test/inner_product_of
x deepdive-0.7.0/util/test/l2_distance_of
x deepdive-0.7.0/util/test/normalize_by_sum
x deepdive-0.7.0/util/test/probability_distribution_of
x deepdive-0.7.0/util/test/sqrt
x deepdive-0.7.0/util/test/squares
x deepdive-0.7.0/util/test/sum
x deepdive-0.7.0/util/test/unit_vector
+ date
## Finished installation for deepdive_examples_tests
+ PATH=/Users/cliu/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ deepdive-0.7.0/test/test-installed.sh
/dev/fd/63: line 136: deepdive-0.7.0/test/test-installed.sh: No such file or directory
## Failed installation for run_deepdive_tests
```

BTW, I installed PostgreSQL 9.4 together with deepdive. PostgreSQL seems working fine, which responds to psql command smoothly. 

Thank you very much for your help. 
Best,
Lee

**Comment by zhangce** [comment]
@netj Can you help with this one? Sorry I am not that familiar with the current installer of DD. Thanks!

**Comment by netj** [comment]
Hi @ukliu, sorry but `run_deepdive_tests` option has been added after 0.7.0 was released, so the release itself doesn't support testing installation, but you can run tests with the maintenance branch.  Try:
```bash
RELEASE=v0.7.x  bash <(curl -fsSL deepdive.stanford.edu/install) run_deepdive_tests
```

**Comment by ukliu** [comment]
@netj  Thanks so much for the prompt reply! I tried it, but it failed for most of the tests. The error message is like this.
...
remote: Counting objects: 574, done.
remote: Total 574 (delta 0), reused 0 (delta 0), pack-reused 574
Receiving objects: 100% (574/574), 114.06 KiB | 0 bytes/s, done.
Resolving deltas: 100% (270/270), done.
Checking connectivity... done.
Testing against database TEST_DBNAME=deepdive_test_cliu running at TEST_DBHOST=localhost
Running 13 tests defined in 6 .bats files: test/postgresql/biased_coin_example.bats test/postgresql/broken_example.bats test/postgresql/chunking_example.bats test/postgresql/spouse_example.bats test/postgresql/spouse_example_incremental.bats test/test_plpy.bats
 ✓ postgresql biased coin example
 ✓ postgresql DeepDive returns error for a broken application
 ✗ postgresql chunking example
   (in test file test/postgresql/chunking_example.bats, line 11)
     `DEEPDIVE_CONFIG_EXTRA='deepdive.calibration.holdout_query: "INSERT INTO dd_graph_variables_holdout(variable_id) SELECT id FROM words WHERE word_id > '${SUBSAMPLE_NUM_WORDS_TRAIN}'"' \' failed with status 137
   CREATE TABLE
   CREATE TABLE
   CREATE TABLE
   COPY 6000
   20:07:41 [] INFO  Slf4jLogger started
   20:07:41 [EventStream(akka://deepdive)] DEBUG logger log1-Slf4jLogger started
   20:07:41 [EventStream(akka://deepdive)] DEBUG Default Loggers started
   20:07:41 [Main$(akka://deepdive)] INFO  Running pipeline with configuration from /var/folders/f7/4rfwnx6j1vv_rksgtbydk57r0000gn/T/deepdive.conf.iezYANp
   20:07:41 [SettingsParser$(akka://deepdive)] INFO  Database settings: user cliu, dbname deepdive_test_cliu, host localhost, port 5432.
   20:07:41 [SettingsParser$(akka://deepdive)] DEBUG samplerArgs: -l 300 -s 1 -i 500 --alpha 0.1
   20:07:41 [DeepDive$(akka://deepdive)] DEBUG relearnFrom=null
   20:07:41 [DeepDive$(akka://deepdive)] DEBUG outputDir=/Users/cliu/deepdive-0.7.x/examples/chunking/run/20150921/200740.N
   20:07:41 [JdbcDataStoreObject$(akka://deepdive)] INFO  Intializing all JDBC data stores
   20:07:41 [profiler] INFO  starting at akka://deepdive/user/profiler
   20:07:41 [taskManager] INFO  starting at akka://deepdive/user/taskManager
   20:07:41 [inferenceManager] INFO  Starting
   20:07:41 [extractionManager] INFO  starting
   20:07:41 [PostgresDataStore(akka://deepdive)] DEBUG Executing SQL with callback... SELECT EXISTS (
         SELECT 1
         FROM   pg_language
         WHERE  lanname = 'plpgsql');
   20:07:41 [DeepDive$(akka://deepdive)] DEBUG Total number of extractors: 2
   20:07:41 [DeepDive$(akka://deepdive)] DEBUG Total number of factors: 3
   20:07:41 [DeepDive$(akka://deepdive)] DEBUG Number of active factors: 3
   20:07:41 [DeepDive$(akka://deepdive)] INFO  Running pipeline=_default with tasks=List(ext_features, ext_training, inference_grounding, inference, calibration, report, shutdown)
   20:07:41 [taskManager] INFO  Added task_id=ext_features
   20:07:41 [taskManager] INFO  Added task_id=ext_training
   20:07:41 [taskManager] DEBUG Sending task_id=ext_training to Actor[akka://deepdive/user/extractionManager#-189704169]
   20:07:41 [profiler] DEBUG starting report_id=ext_training
   20:07:41 [taskManager] INFO  Added task_id=inference_grounding
   20:07:41 [taskManager] INFO  Added task_id=inference
   20:07:41 [taskManager] INFO  Added task_id=calibration
   20:07:41 [taskManager] INFO  Added task_id=report
   20:07:41 [taskManager] INFO  Added task_id=shutdown
   20:07:41 [PostgresDataStore(akka://deepdive)] DEBUG Executing SQL with callback... SELECT EXISTS (
         SELECT 1
         FROM   pg_language
         WHERE  lanname = 'plpythonu');
   20:07:41 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: CREATE LANGUAGE plpythonu
   20:07:41 [PostgresDataStore(akka://deepdive)] ERROR org.postgresql.util.PSQLException: ERROR: could not access file "$libdir/plpython2": No such file or directory
   20:07:41 [extractionManager] ERROR ERROR: could not access file "$libdir/plpython2": No such file or directory
   akka.actor.ActorInitializationException: exception during creation
   	at akka.actor.ActorInitializationException$.apply(Actor.scala:166) ~[deepdive.jar:0.7.0]
   	at akka.actor.ActorCell.create(ActorCell.scala:571) ~[deepdive.jar:0.7.0]
   	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:431) ~[deepdive.jar:0.7.0]
   	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:453) ~[deepdive.jar:0.7.0]
   	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262) ~[deepdive.jar:0.7.0]
   	at akka.dispatch.Mailbox.run(Mailbox.scala:218) ~[deepdive.jar:0.7.0]
   	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) [deepdive.jar:0.7.0]
   	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [deepdive.jar:0.7.0]
   	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [deepdive.jar:0.7.0]
   	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [deepdive.jar:0.7.0]
   	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [deepdive.jar:0.7.0]
   Caused by: org.postgresql.util.PSQLException: ERROR: could not access file "$libdir/plpython2": No such file or directory
   	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157) ~[deepdive.jar:0.7.0]
   	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886) ~[deepdive.jar:0.7.0]
   	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[deepdive.jar:0.7.0]
   	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555) ~[deepdive.jar:0.7.0]
   	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417) ~[deepdive.jar:0.7.0]
   	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:410) ~[deepdive.jar:0.7.0]
   	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[deepdive.jar:0.7.0]
   	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[deepdive.jar:0.7.0]
   	at org.deepdive.datastore.JdbcDataStore$$anonfun$executeSqlQueries$2.apply(JdbcDataStore.scala:90) ~[deepdive.jar:0.7.0]
   	at org.deepdive.datastore.JdbcDataStore$$anonfun$executeSqlQueries$2.apply(JdbcDataStore.scala:87) ~[deepdive.jar:0.7.0]
   	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[deepdive.jar:0.7.0]
   	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108) ~[deepdive.jar:0.7.0]
   	at org.deepdive.datastore.JdbcDataStore$class.executeSqlQueries(JdbcDataStore.scala:87) ~[deepdive.jar:0.7.0]
   	at org.deepdive.datastore.PostgresDataStore.executeSqlQueries(PostgresDataStore.scala:20) ~[deepdive.jar:0.7.0]
   	at org.deepdive.datastore.PostgresDataStore.init(PostgresDataStore.scala:182) ~[deepdive.jar:0.7.0]
   	at org.deepdive.extraction.ExtractionManager$class.preStart(ExtractionManager.scala:64) ~[deepdive.jar:0.7.0]
   	at org.deepdive.extraction.ExtractionManager$PostgresExtractionManager.preStart(ExtractionManager.scala:28) ~[deepdive.jar:0.7.0]
   	at akka.actor.Actor$class.aroundPreStart(Actor.scala:472) ~[deepdive.jar:0.7.0]
   	at org.deepdive.extraction.ExtractionManager$PostgresExtractionManager.aroundPreStart(ExtractionManager.scala:28) ~[deepdive.jar:0.7.0]
   	at akka.actor.ActorCell.create(ActorCell.scala:555) ~[deepdive.jar:0.7.0]
   	... 9 common frames omitted
   20:07:41 [taskManager] INFO  Actor[akka://deepdive/user/extractionManager#-189704169] was terminated. Canceling its tasks.
   20:07:41 [profiler] DEBUG ending report_id=ext_training
   20:07:41 [taskManager] INFO  Completed task_id=ext_training with Failure(java.lang.RuntimeException: worker was terminated)
   20:07:41 [taskManager] ERROR task=ext_training Failed: java.lang.RuntimeException: worker was terminated
   20:07:41 [taskManager] ERROR Forcing shutdown
   20:07:41 [taskManager] ERROR Cancelling task=inference_grounding
   20:07:41 [taskManager] ERROR Cancelling task=calibration
   20:07:41 [taskManager] ERROR Cancelling task=inference
   20:07:41 [taskManager] ERROR Cancelling task=ext_features
   /Users/cliu/local/util/deepdive-run: line 80:  8035 Killed: 9               java org.deepdive.Main -c "$extendedConfig" -o "$APP_HOME/$run_dir"
 ✗ postgresql spouse example (tsv_extractor)
...
 ✗ postgresql spouse example (json_extractor)
..
 ✗ postgresql spouse example (piggy_extractor)
...
 - postgresql spouse example (plpy_extractor) (skipped)
 ✗ incremental spouse example (F1, then F2 and Symmetry incrementally)
...
...
...
13 tests, 9 failures, 1 skipped
## Failed installation for run_deepdive_tests

Could you please take a look at it? Thanks!

**Comment by netj** [comment]
@ukliu I see.  It seems your postgresql is not installed with plpython support.  We are trying to eliminate that dependency in the next release, but for now you can reinstall it with:
```
brew uninstall postgresql
brew install postgresql --with-python
```
 or use our installer's postgresql option.

**Comment by ukliu** [comment]
@netj  Thank you so much! Now everything is working!
One of the 13 tests is skipped. I guess that is acceptable, right?


### DeepDive installer for Mac
+ curl -fsSL https://github.com/HazyResearch/deepdive/raw/v0.7.x/util/install/install.Mac.sh
## Starting installation for run_deepdive_tests
## Starting installation for deepdive_examples_tests
DeepDive examples and tests already downloaded at /Users/cliu/deepdive-0.7.x
## Finished installation for deepdive_examples_tests
+ PATH=/Users/cliu/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ deepdive-0.7.x/test/test-installed.sh
Testing DeepDive installed at: /Users/cliu/local
Testing against database TEST_DBNAME=deepdive_test_cliu running at TEST_DBHOST=localhost
Running 13 tests defined in 6 .bats files: test/postgresql/biased_coin_example.bats test/postgresql/broken_example.bats test/postgresql/chunking_example.bats test/postgresql/spouse_example.bats test/postgresql/spouse_example_incremental.bats test/test_plpy.bats
 ✓ postgresql biased coin example
 ✓ postgresql DeepDive returns error for a broken application
 ✓ postgresql chunking example
 ✓ postgresql spouse example (tsv_extractor)
 ✓ postgresql spouse example (json_extractor)
 ✓ postgresql spouse example (piggy_extractor)
 - postgresql spouse example (plpy_extractor) (skipped)
 ✓ incremental spouse example (F1, then F2 and Symmetry incrementally)
 ✓ incremental spouse example's non-incremental run (F1+F2)
 ✓ incremental spouse example's non-incremental run (F1+F2+Symmetry)
 ✓ similarity of probability distributions of incremental and non-incremental spouse example (F1+F2)
 ✓ similarity of probability distributions of incremental and non-incremental spouse example (F1+F2+Symmetry)
 ✓ util/ddext.py should work as expected

13 tests, 0 failures, 1 skipped
## Finished installation for run_deepdive_tests

**Comment by netj** [comment]
Glad it helped!  Yes, that test is for a deprecated feature and intentionally skipped.
