### ISSUE TITLE
install error,  curl: (23) Failed writing body (0 != 16360)

### ISSUE THREAD

**Issue by eromoe** [HazyResearch/deepdive#651]
Error message:
```
++ get-url https://github.com/HazyResearch/deepdive/raw/master/util/install.sh
++ curl -fsSL https://github.com/HazyResearch/deepdive/raw/master/util/install.sh
### DeepDive installer for Ubuntu
1) deepdive                   6) postgres
2) deepdive_docker_sandbox    7) postgres_xl
3) deepdive_example_notebook  8) run_deepdive_tests
4) deepdive_from_release      9) spouse_example
5) jupyter_notebook
# Install what (enter to repeat options, a to see all, q to quit, or a number)? 1
## Starting installation for deepdive
## Starting installation for deepdive_from_release
# Installing DeepDive release v0.8-STABLE...
# Press any key to select a different release or Enter to proceed...
+ rm -f deepdive-v0.8-STABLE-Linux.tar.gz
+ download https://github.com/HazyResearch/deepdive/releases/download/v0.8-STABLE/deepdive-v0.8-STABLE-Linux.tar.gz
+ local url=https://github.com/HazyResearch/deepdive/releases/download/v0.8-STABLE/deepdive-v0.8-STABLE-Linux.tar.gz
++ basename https://github.com/HazyResearch/deepdive/releases/download/v0.8-STABLE/deepdive-v0.8-STABLE-Linux.tar.gz
+ local file=deepdive-v0.8-STABLE-Linux.tar.gz
++ python -c 'import urllib,sys;print urllib.unquote(sys.argv[1])' deepdive-v0.8-STABLE-Linux.tar.gz
  File "<string>", line 1
    import urllib,sys;print urllib.unquote(sys.argv[1])
                                 ^
SyntaxError: invalid syntax
+ file=
+ [[ -e '' ]]
+ echo '# Downloading https://github.com/HazyResearch/deepdive/releases/download/v0.8-STABLE/deepdive-v0.8-STABLE-Linux.tar.gz'
# Downloading https://github.com/HazyResearch/deepdive/releases/download/v0.8-STABLE/deepdive-v0.8-STABLE-Linux.tar.gz
+ type curl
+ curl -fLRo '' https://github.com/HazyResearch/deepdive/releases/download/v0.8-STABLE/deepdive-v0.8-STABLE-Linux.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   623    0   623    0     0    570      0 --:--:--  0:00:01 --:--:--   571
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Remote filename has no length!
  0 98.6M    0 16360    0     0   6486      0  4:25:44  0:00:02  4:25:42 18279
curl: (23) Failed writing body (0 != 16360)
+ mkdir -p /root/local
+ tar xzvf deepdive-v0.8-STABLE-Linux.tar.gz -C /root/local
tar (child): deepdive-v0.8-STABLE-Linux.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
## Failed installation for deepdive_from_release
## Failed installation for deepdive
# Install what (enter to repeat options, a to see all, q to quit, or a number)?
```

**Comment by eromoe** [comment]
Does deepdive only need python 2 ??
I found it was by file name empty, because `import urllib,sys;print urllib.unquote(sys.argv[1])` not valid in python 3. 

I changed that to  `file=$(python -c 'import sys;from urllib.parse import unquote;print(unquote(sys.argv[1]))' "$file")`

**Comment by winnerineast** [comment]
It seems true based my case.

**Comment by eromoe** [comment]
Anyway, installation is buggy on python3 , I also see some error as
```
Setting up python-software-properties (0.92.37.8) ...
+ false
+ sudo add-apt-repository -y ppa:openjdk-r/ppa
+ [[ 0 = 0 ]]
+ add-apt-repository -y ppa:openjdk-r/ppa
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 11, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 27, in <module>
    import apt_pkg
ImportError: No module named 'apt_pkg'
```

Finally , I give up and turn to python2 ,   and success.

**Comment by ofersabo** [comment]
The same thing happened to me, moved to use python2 and it worked.

**Comment by abuhamzakhan** [comment]
![Screenshot from 2019-09-08 13-26-47](https://user-images.githubusercontent.com/55046348/64485661-7a1b7000-d23c-11e9-9a13-c1c8fcbed454.png)
  
can anyone please help me to resolve this issue.. error showing while install minikube
