### ISSUE TITLE
I get the following error while running 'do sentences'

### ISSUE THREAD

**Issue by 13227018679** [HazyResearch/deepdive#667]
2018-03-22 12:36:34.723838 CREATE TABLE
2018-03-22 12:36:34.775074 unloading to feed_processes-1: ' SELECT R0.id AS "articles.R0.id", R0.content AS "articles.R0.content"
2018-03-22 12:36:34.775127 FROM articles R0
2018-03-22 12:36:34.775180         
2018-03-22 12:36:34.775206           '
2018-03-22 12:36:34.799819 Loading dd_tmp_sentences from output_computed-1 (tsv format)
2018-03-22 12:36:35.717367 Parsing with max_len=100
loading dd_tmp_sentences: 0:00:01    0 B [   0 B/s] ([   0 B/s])
loading dd_tmp_sentences: 0:00:01    0  [   0 /s] ([   0 /s])2018-03-22 12:36:36.002293 Adding annotator tokenize
2018-03-22 12:36:36.006138 TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
2018-03-22 12:36:36.010993 Adding annotator cleanxml
2018-03-22 12:36:36.048643 Adding annotator ssplit
2018-03-22 12:36:36.055030 Adding annotator pos
2018-03-22 12:36:36.100778 Exception in thread "main" java.lang.RuntimeException: edu.stanford.nlp.io.RuntimeIOException: Unrecoverable error while loading a tagger model
2018-03-22 12:36:36.101240 	at edu.stanford.nlp.pipeline.AnnotatorFactories$4.create(AnnotatorFactories.java:291)
2018-03-22 12:36:36.101395 	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:85)
2018-03-22 12:36:36.101543 	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:289)
2018-03-22 12:36:36.101684 	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:126)
2018-03-22 12:36:36.101822 	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:122)
2018-03-22 12:36:36.101948 	at com.clearcut.nlp.DocumentParser.<init>(DocumentParser.scala:15)
2018-03-22 12:36:36.102075 	at com.clearcut.nlp.Main$delayedInit$body.apply(Main.scala:66)
2018-03-22 12:36:36.102204 	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
2018-03-22 12:36:36.102478 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
2018-03-22 12:36:36.102631 	at scala.App$$anonfun$main$1.apply(App.scala:71)
2018-03-22 12:36:36.102796 	at scala.App$$anonfun$main$1.apply(App.scala:71)
2018-03-22 12:36:36.102929 	at scala.collection.immutable.List.foreach(List.scala:318)
2018-03-22 12:36:36.103057 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
2018-03-22 12:36:36.103192 	at scala.App$class.main(App.scala:71)
2018-03-22 12:36:36.103326 	at com.clearcut.nlp.Main$.main(Main.scala:10)
2018-03-22 12:36:36.103451 	at com.clearcut.nlp.Main.main(Main.scala)
2018-03-22 12:36:36.103706 Caused by: edu.stanford.nlp.io.RuntimeIOException: Unrecoverable error while loading a tagger model
2018-03-22 12:36:36.103837 	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:769)
2018-03-22 12:36:36.103964 	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:297)
2018-03-22 12:36:36.104091 	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:262)
2018-03-22 12:36:36.104525 	at edu.stanford.nlp.pipeline.POSTaggerAnnotator.loadModel(POSTaggerAnnotator.java:97)
2018-03-22 12:36:36.104679 	at edu.stanford.nlp.pipeline.POSTaggerAnnotator.<init>(POSTaggerAnnotator.java:77)
2018-03-22 12:36:36.104812 	at edu.stanford.nlp.pipeline.AnnotatorImplementations.posTagger(AnnotatorImplementations.java:58)
2018-03-22 12:36:36.104944 	at edu.stanford.nlp.pipeline.AnnotatorFactories$4.create(AnnotatorFactories.java:289)
2018-03-22 12:36:36.105310 	... 15 more
2018-03-22 12:36:36.105553 Caused by: java.io.IOException: Unable to resolve "edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" as either class path, filename or URL
2018-03-22 12:36:36.105687 	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:463)
unloading: 0:00:01  149  [ 116 /s] ([ 116 /s])d.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:764)
loading dd_tmp_sentences: 0:00:01    0 B [   0 B/s] ([   0 B/s])
loading dd_tmp_sentences: 0:00:01    0  [   0 /s] ([   0 /s])cal/compute-execute: line 140: kill: (32142) - No such process
2018-03-22 12:36:36.115691 COPY 0
unloading: 0:00:01  672KiB [ 524KiB/s] ([ 524KiB/s])

**Comment by MahmoudYounes** [comment]
if you are following a tutorial, please, point out the link to the tutorial, otherwise, please post your app.ddlog and any udf you are using to help debug
